//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChungCu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hopdong
    {
        public int mahopdong { get; set; }
        public int manhanvien { get; set; }
        public int macanho { get; set; }
        public int maho { get; set; }
        public string tenhopdong { get; set; }
        public double giatien { get; set; }
        public string thoihan { get; set; }
        public System.DateTime ngayki { get; set; }
        public bool dahuy { get; set; }
    
        public virtual canho canho { private get; set; }
        public virtual hogiadinh hogiadinh { private get; set; }
        public virtual nhanvien nhanvien {  private get; set; }
    }
}
